### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by larsr** [coq-community/corn#160]
I'm trying to update the .nix file for CoRN.
Is would be helpful if you could make a new release with the patch #159, because it is necessary to compile with coq 8.13. 
Thanks.

**Comment by Zimmi48** [comment]
Done. See https://github.com/coq-community/corn/releases/tag/8.13.0, https://github.com/NixOS/nixpkgs/pull/136989 and https://github.com/coq/opam-coq-archive/pull/1807.
