### ISSUE TITLE
Please pick the version you prefer for Coq 8.14 in Coq Platform 2021.11

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/corn#163]
The Coq team released Coq 8.14+rc1 on September 17, 2021 and plans to release Coq 8.14.0 before October 31, 2021.
The corresponding Coq Platform release 2021.11 should be released before November 30, 2021.
It can be delayed in case of difficulties until January 31, 2022, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Coq Platform CI works fine with Coq 8.14+rc1.

Coq Platform CI is currently testing opam package `coq-corn.8.13.0`
from official repository https://coq.inria.fr/opam/released/packages/coq-corn/coq-corn.8.13.0/opam.

In case this is the version you want to see in Coq Platform, there is nothing to do for you - please just close this issue.

In case you would prefer to see an updated or an older version in the upcoming Coq Platform 2021.11, please inform us as soon as possible and before November 15, 2021!

The working branch of Coq Platform, which already supports Coq version 8.14+rc1, can be found here https://github.com/coq/platform/tree/main.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/139

**Comment by spitters** [comment]
I'm guessing we want to transition to 8.14.0 when it's released.
Is there anything that needs to be done now?

**Comment by Zimmi48** [comment]
I don't think so. The latest release is already compatible with 8.14, as Michael mentioned.

**Comment by MSoegtropIMC** [comment]
This issue is to inform you ahead of time and to track things. If it is closed, it means I go with `coq-corn.8.13.0` - which I probably won't do anyway if there will be a `coq-corn.8.14.0`, but as written above, if you want to be safe you should keep this issue open until I did the PR which moves Coq Platform to `coq-corn.8.14.0`.

**Comment by Zimmi48** [comment]
What I meant was: there will be no 8.14.0 release, or at least not for a while, since the 8.13.0 release was done very recently and is compatible with Coq 8.14 already.

**Comment by MSoegtropIMC** [comment]
OK, so if the only change is relaxing the version restrictions in the opam package - however one wants to name it then - it is correct to close this issue. If you decide otherwise before November, please reopen.
