### ISSUE TITLE
Remove all or most compatibility-notation warnings.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/corn#62]
Currently corn emits 1378 such warnings (computed with `make -j4 3>&1- 1>&2- 2>&3- | grep compatibility-notation | wc -l`). @JasonGross has prepared two scripts that should help fixing them (https://github.com/coq/coq/issues/8383#issuecomment-423238820 and https://github.com/coq/coq/issues/8383#issuecomment-423370438). I'm going to test how efficient these are to get rid of compatibility-notation warnings in corn.

**Comment by Zimmi48** [comment]
The first script creates too many problems to be of any help. It changes these lines when it should not:
```
Require Import Coq.ZArith.Zdiv.
Require Export Coq.ZArith.Zmin.
Require Export Coq.ZArith.Zmax.
Lemma Zabs_triangle
```
but it's even worse when the library redefines something like `Zgcd` because then it becomes almost impossible to track down what should have changed and what should have been kept as-is.
This corroborates my previous failed attempts at using `git grep` to fix this kind of warnings.

**Comment by Zimmi48** [comment]
The second script only changed 470 lines. There are still problems when compiling the result but I haven't investigated yet how many.

**Comment by Zimmi48** [comment]
There are replacement problems of the type: `Ppred_succ` becomes `Pos.pred_succuccucc`. @JasonGross: if the character location given by warnings are not good enough but line numbers are correct, what about disregarding character location and doing a search-and-replace on the given line?

**Comment by JasonGross** [comment]
@Zimmi48 I've made an updated version that does that at https://github.com/coq/coq/issues/8383#issuecomment-424516118

**Comment by Zimmi48** [comment]
Thanks!
